// <auto-generated />
using System;
using DevTeamFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevTeamFinder.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DevTeamFinder.Models.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeneyimSeviyesi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hakkinda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("DevTeamFinder.Models.DeveloperSkill", b =>
                {
                    b.Property<int>("DeveloperId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeveloperId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("DeveloperSkills");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Not")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SenderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.HasIndex("SenderId");

                    b.HasIndex("ProjectId", "DeveloperId")
                        .IsUnique();

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DevTeamFinder.Models.ProjectSkill", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ProjectSkills");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "ASP.NET MVC"
                        },
                        new
                        {
                            Id = 4,
                            Ad = ".NET"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Entity Framework"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Java"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Spring Boot"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Python"
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Django"
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Flask"
                        },
                        new
                        {
                            Id = 11,
                            Ad = "JavaScript"
                        },
                        new
                        {
                            Id = 12,
                            Ad = "TypeScript"
                        },
                        new
                        {
                            Id = 13,
                            Ad = "React"
                        },
                        new
                        {
                            Id = 14,
                            Ad = "Angular"
                        },
                        new
                        {
                            Id = 15,
                            Ad = "Vue.js"
                        },
                        new
                        {
                            Id = 16,
                            Ad = "Node.js"
                        },
                        new
                        {
                            Id = 17,
                            Ad = "Express.js"
                        },
                        new
                        {
                            Id = 18,
                            Ad = "HTML"
                        },
                        new
                        {
                            Id = 19,
                            Ad = "CSS"
                        },
                        new
                        {
                            Id = 20,
                            Ad = "Tailwind CSS"
                        },
                        new
                        {
                            Id = 21,
                            Ad = "Bootstrap"
                        },
                        new
                        {
                            Id = 22,
                            Ad = "Flutter"
                        },
                        new
                        {
                            Id = 23,
                            Ad = "Dart"
                        },
                        new
                        {
                            Id = 24,
                            Ad = "Kotlin"
                        },
                        new
                        {
                            Id = 25,
                            Ad = "Swift"
                        },
                        new
                        {
                            Id = 26,
                            Ad = "iOS"
                        },
                        new
                        {
                            Id = 27,
                            Ad = "Android"
                        },
                        new
                        {
                            Id = 28,
                            Ad = "SQL"
                        },
                        new
                        {
                            Id = 29,
                            Ad = "PostgreSQL"
                        },
                        new
                        {
                            Id = 30,
                            Ad = "MySQL"
                        },
                        new
                        {
                            Id = 31,
                            Ad = "MongoDB"
                        },
                        new
                        {
                            Id = 32,
                            Ad = "Redis"
                        },
                        new
                        {
                            Id = 33,
                            Ad = "Docker"
                        },
                        new
                        {
                            Id = 34,
                            Ad = "Kubernetes"
                        },
                        new
                        {
                            Id = 35,
                            Ad = "Git"
                        },
                        new
                        {
                            Id = 36,
                            Ad = "GitHub"
                        },
                        new
                        {
                            Id = 37,
                            Ad = "DevOps"
                        },
                        new
                        {
                            Id = 38,
                            Ad = "CI/CD"
                        },
                        new
                        {
                            Id = 39,
                            Ad = "Azure"
                        },
                        new
                        {
                            Id = 40,
                            Ad = "AWS"
                        },
                        new
                        {
                            Id = 41,
                            Ad = "Firebase"
                        },
                        new
                        {
                            Id = 42,
                            Ad = "REST API"
                        },
                        new
                        {
                            Id = 43,
                            Ad = "GraphQL"
                        });
                });

            modelBuilder.Entity("DevTeamFinder.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Developer", b =>
                {
                    b.HasOne("DevTeamFinder.Models.User", "User")
                        .WithOne("Developer")
                        .HasForeignKey("DevTeamFinder.Models.Developer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DevTeamFinder.Models.DeveloperSkill", b =>
                {
                    b.HasOne("DevTeamFinder.Models.Developer", "Developer")
                        .WithMany("DeveloperSkills")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevTeamFinder.Models.Skill", "Skill")
                        .WithMany("DeveloperSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Invitation", b =>
                {
                    b.HasOne("DevTeamFinder.Models.Developer", "Developer")
                        .WithMany("Invitations")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevTeamFinder.Models.Project", "Project")
                        .WithMany("Invitations")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevTeamFinder.Models.Developer", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Developer");

                    b.Navigation("Project");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Project", b =>
                {
                    b.HasOne("DevTeamFinder.Models.Developer", "Developer")
                        .WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("DevTeamFinder.Models.ProjectSkill", b =>
                {
                    b.HasOne("DevTeamFinder.Models.Project", "Project")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevTeamFinder.Models.Skill", "Skill")
                        .WithMany("ProjectSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Developer", b =>
                {
                    b.Navigation("DeveloperSkills");

                    b.Navigation("Invitations");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Project", b =>
                {
                    b.Navigation("Invitations");

                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("DevTeamFinder.Models.Skill", b =>
                {
                    b.Navigation("DeveloperSkills");

                    b.Navigation("ProjectSkills");
                });

            modelBuilder.Entity("DevTeamFinder.Models.User", b =>
                {
                    b.Navigation("Developer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
